# Add the presence of the bot.
# status — online / idle / dnd / invisible
# type — 0 (Playing) / 1 (Streaming) / 2 (Listening) / 3 (Watching) /  4 (Custom Status) / 5 (Competing)
presence:
  status: 'online'
  activities:
    - name: '/help'
      type: 4

# When enabled, this enables debug mode for the bot.
# This will log all the events and commands to the console.
# `DEBUG_MODE` and `DEBUG` environment variable overwrites this value.
debugMode: false

# This is used to set the default permissions for commands.
defaultPermissions:
  - 'SendMessages'
  - 'ViewChannel'
