- name: 'blocked'
  color: 'd81a0d'
- name: 'bug'
  color: 'd73a4a'
- name: 'chore'
  color: 'ffffff'
- name: 'ci'
  color: '0075ca'
- name: 'dependencies'
  color: '0025ff'
- name: 'discussion'
  color: 'b6b1f9'
- name: 'documentation'
  color: '0075ca'
- name: 'duplicate'
  color: 'd93f0b'
- name: 'feature request'
  color: 'fcf95a'
- name: 'good first issue'
  color: '7057ff'
- name: 'has PR'
  color: '4b1f8e'
- name: 'help wanted'
  color: '008672'
- name: 'in progress'
  color: 'ffccd7'
- name: 'in review'
  color: 'aed5fc'
- name: 'invalid'
  color: 'e4e669'
- name: 'need repro'
  color: 'c66037'
- name: 'performance'
  color: '80c042'
- name: 'priority:critical'
  color: 'b60205'
- name: 'priority:high'
  color: 'd93f0b'
- name: 'priority:medium'
  color: 'fbca04'
- name: 'priority:low'
  color: '0e8a16'
- name: 'question'
  color: 'cc317c'
- name: 'security'
  color: 'ee0701'
- name: 'semver:major'
  color: 'c10f47'
- name: 'semver:minor'
  color: 'e4f486'
- name: 'semver:patch'
  color: 'e8be8b'
- name: 'wontfix'
  color: 'f9d0c4'
