# General labels
- name: 'semver:major'
  color: 'c10f47'
- name: 'semver:minor'
  color: 'e4f486'
- name: 'semver:patch'
  color: 'e8be8b'
- name: 'blocked'
  color: 'd81a0d'
- name: 'question'
  color: 'd876e3'
- name: 'regression'
  color: 'ea8785'
- name: 'wontfix'
  color: 'f9d0c4'
- name: 'chore'
  color: 'b6b1f9'
- name: 'ci'
  color: '0075ca'
- name: 'dependencies'
  color: '276bd1'
- name: 'duplicate'
  color: 'd93f0b'
- name: 'feature request'
  color: 'fcf95a'
- name: 'bug'
  color: 'd73a4a'
- name: 'backlog'
  color: '7ef7ef'
- name: 'priority:high'
  color: 'd93f0b'
- name: 'security'
  color: 'ee0701'
- name: 'good first issue'
  color: '7057ff'
- name: 'has PR'
  color: '4b1f8e'
- name: 'help wanted'
  color: '008672'
- name: 'in progress'
  color: 'ffccd7'

# Monorepo labels
- name: 'apps:bot'
  color: 'cc317c'
- name: 'apps:website'
  color: 'cc317c'
- name: 'packages:database'
  color: 'c66037'
- name: 'packages:logger'
  color: 'c66037'
- name: 'packages:tesseract'
  color: 'c66037'
- name: 'packages:ui'
  color: 'c66037'
- name: 'packages:utils'
  color: 'c66037'
