apps:bot:
  - changed-files:
      - any-glob-to-any-file: ['apps/bot/*', 'apps/bot/**/*']
apps:web:
  - changed-files:
      - any-glob-to-any-file: ['apps/web/*', 'apps/web/**/*']
packages:core:
  - changed-files:
      - any-glob-to-any-file: ['packages/core/*', 'packages/core/**/*']
packages:database:
  - changed-files:
      - any-glob-to-any-file: ['packages/database/*', 'packages/database/**/*']
packages:logger:
  - changed-files:
      - any-glob-to-any-file: ['packages/logger/*', 'packages/logger/**/*']
packages:ui:
  - changed-files:
      - any-glob-to-any-file: ['packages/ui/*', 'packages/ui/**/*']
packages:utils:
  - changed-files:
      - any-glob-to-any-file: ['packages/utils/*', 'packages/utils/**/*']
