apps:bot:
  - changed-files:
      - any-glob-to-any-file: ['apps/bot/*', 'apps/bot/**/*']
apps:website:
  - changed-files:
      - any-glob-to-any-file: ['apps/website/*', 'apps/website/**/*']
packages:database:
  - changed-files:
      - any-glob-to-any-file: ['packages/database/*', 'packages/database/**/*']
packages:logger:
  - changed-files:
      - any-glob-to-any-file: ['packages/logger/*', 'packages/logger/**/*']
packages:ui:
  - changed-files:
      - any-glob-to-any-file: ['packages/ui/*', 'packages/ui/**/*']
packages:utils:
  - changed-files:
      - any-glob-to-any-file: ['packages/utils/*', 'packages/utils/**/*']
packages:webserver:
  - changed-files:
      - any-glob-to-any-file: ['packages/webserver/*', 'packages/webserver/**/*']
