allowBuilds:
  '@prisma/engines': true
  '@sapphire/type': true
  '@swc/core': true
  bufferutil: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

autoInstallPeers: true

minimumReleaseAge: 0

packages:
  - 'apps/*'
  - 'packages/*'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*types*'
  - '!@types/react'
  - '!@types/react-dom'
  - '*discordjs*'
  - '*prisma*'

resolutionMode: 'highest'
