autoInstallPeers: true

resolutionMode: 'highest'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*types*'
  - '!@types/react'
  - '!@types/react-dom'
  - '*discordjs*'
  - '*prisma*'

packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sapphire/type'
  - '@swc/core'
  - '@vercel/speed-insights'
  - 'bufferutil'
  - 'esbuild'
  - 'prisma'
  - 'sharp'
